"""portfolio foreign keys not null

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 08:07:06.906328
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holdings', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('portfolio_snapshots', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('target_allocations', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_allocations', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('portfolio_snapshots', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('holdings', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
